spring.application.name=loan-origination-service
server.port=8080
spring.jpa.hibernate.ddl-auto=validate
# Activates Flyway so versioned SQL migration scripts are applied automatically on startup
spring.flyway.enabled=true
spring.datasource.url=jdbc:postgresql://ep-sweet-butterfly-za6mjjd8.c-2.eu-west-2.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_syZ0o8lpmDWH
# Disables binding the JPA EntityManager to the HTTP request lifecycle, preventing connection-leak and lazy-loading anti-patterns
spring.jpa.open-in-view=false

#spring.security.user.name=anaya
#spring.security.user.password=1234
server.servlet.session.cookie.same-site=strict
